#!/usr/bin/env python3
"""
Generate small notification icons as LVGL C arrays (ARGB8888).
Each icon is 20x20 pixels, white on transparent background.
They will be tinted by the colored circle behind them.
"""
from PIL import Image, ImageDraw
import struct, sys, os

SIZE = 20

def make_phone_icon():
    """Phone handset icon."""
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Classic phone handset shape
    d.rounded_rectangle([4, 3, 16, 17], radius=3, fill=(255, 255, 255, 255))
    # Cut out the middle to make handset shape
    d.rectangle([6, 7, 14, 13], fill=(0, 0, 0, 0))
    # Earpiece
    d.rounded_rectangle([5, 2, 15, 6], radius=2, fill=(255, 255, 255, 255))
    # Mouthpiece
    d.rounded_rectangle([5, 14, 15, 18], radius=2, fill=(255, 255, 255, 255))
    # Connector
    d.rectangle([8, 6, 12, 14], fill=(255, 255, 255, 255))
    d.rectangle([9, 7, 11, 13], fill=(0, 0, 0, 0))
    return img

def make_whatsapp_icon():
    """WhatsApp-style chat bubble with phone."""
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Chat bubble
    d.ellipse([2, 1, 18, 15], fill=(255, 255, 255, 255))
    # Tail
    d.polygon([(4, 13), (2, 18), (8, 14)], fill=(255, 255, 255, 255))
    # Phone handset inside (small)
    d.ellipse([6, 4, 14, 12], fill=(0, 0, 0, 0))
    d.ellipse([7, 5, 13, 11], fill=(255, 255, 255, 255))
    # Cut to make handset shape
    d.rectangle([8, 6, 12, 10], fill=(0, 0, 0, 0))
    d.rectangle([9, 5, 11, 11], fill=(255, 255, 255, 255))
    d.rectangle([10, 6, 10, 10], fill=(0, 0, 0, 0))
    return img

def make_gmail_icon():
    """Gmail-style M envelope."""
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Envelope body
    d.rounded_rectangle([2, 4, 18, 16], radius=2, fill=(255, 255, 255, 255))
    # M shape (cut lines)
    d.line([(2, 4), (10, 11), (18, 4)], fill=(0, 0, 0, 0), width=2)
    # Re-draw M on top for visibility
    d.polygon([(2, 4), (10, 10), (18, 4)], fill=None, outline=(255, 255, 255, 255))
    d.line([(3, 5), (10, 10)], fill=(0, 0, 0, 0), width=2)
    d.line([(17, 5), (10, 10)], fill=(0, 0, 0, 0), width=2)
    return img

def make_envelope_icon():
    """Simple envelope for Apple Mail."""
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Envelope body
    d.rounded_rectangle([2, 5, 18, 16], radius=2, fill=(255, 255, 255, 255))
    # Flap
    d.polygon([(2, 5), (10, 11), (18, 5)], fill=(255, 255, 255, 255), outline=(0, 0, 0, 0))
    # Flap lines
    d.line([(2, 5), (10, 11)], fill=(0, 0, 0, 0), width=1)
    d.line([(18, 5), (10, 11)], fill=(0, 0, 0, 0), width=1)
    return img

def make_calendar_icon():
    """Calendar page icon."""
    img = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    # Page body
    d.rounded_rectangle([3, 3, 17, 17], radius=2, fill=(255, 255, 255, 255))
    # Top bar
    d.rectangle([3, 3, 17, 7], fill=(255, 255, 255, 255))
    # Rings
    d.rectangle([6, 1, 8, 5], fill=(255, 255, 255, 255))
    d.rectangle([12, 1, 14, 5], fill=(255, 255, 255, 255))
    # Grid lines - horizontal
    d.line([(5, 10), (15, 10)], fill=(0, 0, 0, 0), width=1)
    d.line([(5, 13), (15, 13)], fill=(0, 0, 0, 0), width=1)
    # Grid lines - vertical
    d.line([(8, 8), (8, 15)], fill=(0, 0, 0, 0), width=1)
    d.line([(12, 8), (12, 15)], fill=(0, 0, 0, 0), width=1)
    return img

def img_to_c_array(img, name):
    """Convert RGBA image to LVGL ARGB8888 C array."""
    w, h = img.size
    pixels = list(img.getdata())

    lines = []
    lines.append(f"/* Auto-generated by gen_notif_icons.py — do not edit */")
    lines.append(f"#include \"lvgl.h\"")
    lines.append(f"")
    lines.append(f"static const uint8_t {name}_map[] = {{")

    for y in range(h):
        row = "    "
        for x in range(w):
            r, g, b, a = pixels[y * w + x]
            # LVGL ARGB8888: B, G, R, A (little-endian)
            row += f"0x{b:02x}, 0x{g:02x}, 0x{r:02x}, 0x{a:02x}, "
        lines.append(row)

    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"const lv_image_dsc_t {name} = {{")
    lines.append(f"    .header = {{")
    lines.append(f"        .cf = LV_COLOR_FORMAT_ARGB8888,")
    lines.append(f"        .w = {w},")
    lines.append(f"        .h = {h},")
    lines.append(f"    }},")
    lines.append(f"    .data_size = {w * h * 4},")
    lines.append(f"    .data = {name}_map,")
    lines.append(f"}};")
    return "\n".join(lines)

def main():
    out_dir = os.path.join(os.path.dirname(__file__),
                           "../firmware/esp-brookesia/main")

    icons = {
        "icon_phone":    make_phone_icon(),
        "icon_whatsapp": make_whatsapp_icon(),
        "icon_gmail":    make_gmail_icon(),
        "icon_mail":     make_envelope_icon(),
        "icon_calendar": make_calendar_icon(),
    }

    # Generate one combined C file with all icons
    parts = [
        "/* Auto-generated notification icons — do not edit */",
        "/* Generated by tools/gen_notif_icons.py */",
        "",
        '#include "notif_icons.h"',
        "",
    ]

    header_parts = [
        "#pragma once",
        '#include "lvgl.h"',
        "",
    ]

    for name, img in icons.items():
        c_code = img_to_c_array(img, name)
        # Remove the #include lvgl.h from individual entries
        c_code = c_code.replace('#include "lvgl.h"\n', '')
        c_code = c_code.replace('/* Auto-generated by gen_notif_icons.py — do not edit */\n', '')
        parts.append(c_code)
        header_parts.append(f"LV_IMG_DECLARE({name});")

    header_parts.append("")

    c_path = os.path.join(out_dir, "notif_icons.c")
    h_path = os.path.join(out_dir, "notif_icons.h")

    with open(c_path, "w") as f:
        f.write("\n".join(parts) + "\n")
    with open(h_path, "w") as f:
        f.write("\n".join(header_parts) + "\n")

    print(f"Generated {c_path}")
    print(f"Generated {h_path}")

    # Also save PNGs for preview
    preview_dir = os.path.join(out_dir, "../icons_preview")
    os.makedirs(preview_dir, exist_ok=True)
    for name, img in icons.items():
        scaled = img.resize((80, 80), Image.NEAREST)
        scaled.save(os.path.join(preview_dir, f"{name}.png"))
    print(f"Saved previews to {preview_dir}/")

if __name__ == "__main__":
    main()
